In [1]:
#DATA CLEANING

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import random as rnd
from sklearn import datasets, linear_model
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE

In [3]:
data_linear=pd.read_csv(r"C:\Users\Dell\Desktop\linear regression\April-June_22.csv")
df=pd.DataFrame(data_linear)
print(df.shape)

(1602047, 54)

In [4]:
to_drop=['MOULD_WATER_TEMP_BACK','MOULD_WATER_TEMP_NORTH', 'MOULD_WATER_TEMP_SOUTH','MOULD_WATER_BACK','MOULD_WATER_SOUTH','MOULD_WATER_NORTH','MOULD_BACK_HEATLOSS','MOULD_SOUTH_HEATLOSS','MOULD_NORTH_HEATLOSS']
df.drop(to_drop, inplace=True, axis=1)

In [5]:
print(df.shape)

(1602047, 45)

In [6]:
df.isnull().sum()

DATA_TIME                           0
CAP_OFF_MODE                        0
CAST_ID                             0
GRADE                               0
CARBON                              0
VANADIUM                         4852
TITANIUM                         4808
NIOBIUM                          4253
MANGANESE                           0
PHOSPHORUS                          0
SULPHUR                             0
SILICON                             0
TUNDISH_WEIGHT                      0
TUNDISH_TEMPERATURE                 0
CASTING_SPEED                       0
SLAB_WIDTH                          0
MOULD_LEVEL                         0
MOULD_WATER_FRONT                   0
MOULD_WATER_TEMP_FRONT              0
WATER_INLET_TEMP                    0
MOULD_FRONT_HEATLOSS                0
RING_NARROW_FACEA_WATER_FR_PV       0
RING_NARROW_FACEB_WATER_FR_PV       0
ZONE1A_WATER_FR_PV                  0
ZONE1B_WATER_FR_PV                  0
ZONE2_WATER_FR_PV                   0
ZONE3_WATER_FR_PV                   0
ZONE4I_WATER_FR_PV                  0
ZONE4O_WATER_FR_PV                  0
ZONE5I_WATER_FR_PV                  0
ZONE5O_WATER_FR_PV                  0
CONTI_TUNDISH_TEMPERATURE           0
TOTAL_LEN_CAST                      0
FLY_LEN_CAST                        0
MACHINE_POSITION                    0
STOPPER_POSITION                    0
AR_BACK_PRESSURE                    0
AR_FLOW_RATE                        0
AR_BACK_PRESSURE_SHROUD             0
AR_FLOW_SHROUD                      0
AR_BACK_PRESSURE_PLATE              0
AR_FLOW_PLATE                       0
AR_BACK_PRESSURE_NOZZLE             0
AR_FLOW_NOZZLE                      0
TUND_POS                            0
dtype: int64

In [7]:
df.notnull().head()

,DATA_TIME,CAP_OFF_MODE,CAST_ID,GRADE,CARBON,VANADIUM,TITANIUM,NIOBIUM,MANGANESE,PHOSPHORUS,...,STOPPER_POSITION,AR_BACK_PRESSURE,AR_FLOW_RATE,AR_BACK_PRESSURE_SHROUD,AR_FLOW_SHROUD,AR_BACK_PRESSURE_PLATE,AR_FLOW_PLATE,AR_BACK_PRESSURE_NOZZLE,AR_FLOW_NOZZLE,TUND_POS
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [8]:
df.dropna(axis=0,inplace=True,how='any')

In [9]:
df.shape

(1597195, 45)

In [10]:
df.isnull().sum()

DATA_TIME                        0
CAP_OFF_MODE                     0
CAST_ID                          0
GRADE                            0
CARBON                           0
VANADIUM                         0
TITANIUM                         0
NIOBIUM                          0
MANGANESE                        0
PHOSPHORUS                       0
SULPHUR                          0
SILICON                          0
TUNDISH_WEIGHT                   0
TUNDISH_TEMPERATURE              0
CASTING_SPEED                    0
SLAB_WIDTH                       0
MOULD_LEVEL                      0
MOULD_WATER_FRONT                0
MOULD_WATER_TEMP_FRONT           0
WATER_INLET_TEMP                 0
MOULD_FRONT_HEATLOSS             0
RING_NARROW_FACEA_WATER_FR_PV    0
RING_NARROW_FACEB_WATER_FR_PV    0
ZONE1A_WATER_FR_PV               0
ZONE1B_WATER_FR_PV               0
ZONE2_WATER_FR_PV                0
ZONE3_WATER_FR_PV                0
ZONE4I_WATER_FR_PV               0
ZONE4O_WATER_FR_PV               0
ZONE5I_WATER_FR_PV               0
ZONE5O_WATER_FR_PV               0
CONTI_TUNDISH_TEMPERATURE        0
TOTAL_LEN_CAST                   0
FLY_LEN_CAST                     0
MACHINE_POSITION                 0
STOPPER_POSITION                 0
AR_BACK_PRESSURE                 0
AR_FLOW_RATE                     0
AR_BACK_PRESSURE_SHROUD          0
AR_FLOW_SHROUD                   0
AR_BACK_PRESSURE_PLATE           0
AR_FLOW_PLATE                    0
AR_BACK_PRESSURE_NOZZLE          0
AR_FLOW_NOZZLE                   0
TUND_POS                         0
dtype: int64

In [11]:
df.duplicated().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of 0          False
1          False
2          False
3          False
4          False
           ...
1602042    False
1602043    False
1602044    False
1602045    False
1602046    False
Length: 1597195, dtype: bool>

In [12]:
df.drop_duplicates()

,DATA_TIME,CAP_OFF_MODE,CAST_ID,GRADE,CARBON,VANADIUM,TITANIUM,NIOBIUM,MANGANESE,PHOSPHORUS,...,STOPPER_POSITION,AR_BACK_PRESSURE,AR_FLOW_RATE,AR_BACK_PRESSURE_SHROUD,AR_FLOW_SHROUD,AR_BACK_PRESSURE_PLATE,AR_FLOW_PLATE,AR_BACK_PRESSURE_NOZZLE,AR_FLOW_NOZZLE,TUND_POS
0,2022-03-27 09:44:57,0,74177,I17021,0.061,0.005,0.024,0.012,0.745,0.018,...,25.568,2.116,6.097,0.772,82.962,0.013,5.647,1.504,7.708,40.0
1,2022-03-27 09:45:02,0,74177,I17021,0.061,0.005,0.024,0.012,0.745,0.018,...,27.057,2.118,6.102,0.762,82.990,0.013,5.646,1.506,7.722,41.0
2,2022-03-27 09:45:07,0,74177,I17021,0.061,0.005,0.024,0.012,0.745,0.018,...,26.496,2.119,6.104,0.771,82.890,0.013,5.646,1.504,7.702,41.0
3,2022-03-27 09:45:12,0,74177,I17021,0.061,0.005,0.024,0.012,0.745,0.018,...,26.105,2.116,6.096,0.773,82.904,0.013,5.646,1.504,7.708,40.0
4,2022-03-27 09:45:17,0,74177,I17021,0.061,0.005,0.024,0.012,0.745,0.018,...,26.105,2.116,6.095,0.773,83.011,0.013,5.647,1.501,7.725,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1602042,2022-06-29 05:59:34,0,80800,T01403,0.031,0.001,0.001,0.000,0.193,0.019,...,24.762,2.476,7.545,0.928,91.963,0.085,7.244,0.433,7.423,124.0
1602043,2022-06-29 05:59:39,0,80800,T01403,0.031,0.001,0.001,0.000,0.193,0.019,...,23.370,2.474,7.548,0.928,91.984,0.085,7.243,0.434,7.423,124.0
1602044,2022-06-29 05:59:44,0,80800,T01403,0.031,0.001,0.001,0.000,0.193,0.019,...,23.126,2.473,7.549,0.928,91.939,0.085,7.243,0.434,7.423,125.0
1602045,2022-06-29 05:59:49,0,80800,T01403,0.031,0.001,0.001,0.000,0.193,0.019,...,24.811,2.473,7.549,0.929,91.941,0.085,7.244,0.431,7.423,124.0
1602046,2022-06-29 05:59:55,0,80800,T01403,0.031,0.001,0.001,0.000,0.193,0.019,...,23.468,2.473,7.549,0.928,91.940,0.085,7.244,0.435,7.427,124.0

In [13]:
df.dtypes

DATA_TIME                         object
CAP_OFF_MODE                       int64
CAST_ID                            int64
GRADE                             object
CARBON                           float64
VANADIUM                         float64
TITANIUM                         float64
NIOBIUM                          float64
MANGANESE                        float64
PHOSPHORUS                       float64
SULPHUR                          float64
SILICON                          float64
TUNDISH_WEIGHT                   float64
TUNDISH_TEMPERATURE              float64
CASTING_SPEED                    float64
SLAB_WIDTH                       float64
MOULD_LEVEL                      float64
MOULD_WATER_FRONT                float64
MOULD_WATER_TEMP_FRONT           float64
WATER_INLET_TEMP                 float64
MOULD_FRONT_HEATLOSS             float64
RING_NARROW_FACEA_WATER_FR_PV    float64
RING_NARROW_FACEB_WATER_FR_PV    float64
ZONE1A_WATER_FR_PV               float64
ZONE1B_WATER_FR_PV               float64
ZONE2_WATER_FR_PV                float64
ZONE3_WATER_FR_PV                float64
ZONE4I_WATER_FR_PV               float64
ZONE4O_WATER_FR_PV               float64
ZONE5I_WATER_FR_PV               float64
ZONE5O_WATER_FR_PV               float64
CONTI_TUNDISH_TEMPERATURE        float64
TOTAL_LEN_CAST                   float64
FLY_LEN_CAST                     float64
MACHINE_POSITION                 float64
STOPPER_POSITION                 float64
AR_BACK_PRESSURE                 float64
AR_FLOW_RATE                     float64
AR_BACK_PRESSURE_SHROUD          float64
AR_FLOW_SHROUD                   float64
AR_BACK_PRESSURE_PLATE           float64
AR_FLOW_PLATE                    float64
AR_BACK_PRESSURE_NOZZLE          float64
AR_FLOW_NOZZLE                   float64
TUND_POS                         float64
dtype: object

In [14]:
#Completed data cleaning
#Data preprocessing

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
df.drop('GRADE', inplace=True, axis=1)

In [17]:
df.shape

(1597195, 44)

In [18]:
df.describe()

,CAP_OFF_MODE,CAST_ID,CARBON,VANADIUM,TITANIUM,NIOBIUM,MANGANESE,PHOSPHORUS,SULPHUR,SILICON,...,STOPPER_POSITION,AR_BACK_PRESSURE,AR_FLOW_RATE,AR_BACK_PRESSURE_SHROUD,AR_FLOW_SHROUD,AR_BACK_PRESSURE_PLATE,AR_FLOW_PLATE,AR_BACK_PRESSURE_NOZZLE,AR_FLOW_NOZZLE,TUND_POS
count,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,...,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06,1.597195e+06
mean,5.355576e-02,7.745368e+04,1.030548e-01,3.989575e-03,4.000091e-03,7.279222e-03,7.170673e-01,1.847146e-02,6.026532e-03,5.554836e-02,...,2.372764e+01,2.150928e+00,6.103753e+00,7.905857e-01,7.864495e+01,1.922413e-01,5.918600e+00,7.893947e-01,6.923298e+00,9.223092e+01
std,2.251390e-01,2.003646e+03,1.357501e-01,8.518683e-03,8.603679e-03,1.125490e-02,3.703498e-01,7.822410e-03,2.136641e-03,8.871804e-02,...,9.487339e+00,6.441251e-01,2.357622e+00,3.924136e-01,2.612079e+01,2.588407e-01,2.044238e+00,3.465388e-01,2.520300e+00,5.945475e+01
min,0.000000e+00,-1.000000e+00,2.500000e-03,0.000000e+00,0.000000e+00,0.000000e+00,2.600000e-02,5.000000e-03,1.000000e-03,1.000000e-03,...,-1.000000e+00,0.000000e+00,-1.200000e-02,0.000000e+00,-6.000000e-02,-8.700000e-02,-2.600000e-02,-2.560000e-01,-5.100000e-02,0.000000e+00
25%,0.000000e+00,7.586500e+04,4.900000e-02,1.000000e-03,0.000000e+00,0.000000e+00,4.200000e-01,1.400000e-02,5.000000e-03,7.000000e-03,...,1.929200e+01,2.121000e+00,5.742000e+00,6.810000e-01,8.036200e+01,3.100000e-02,5.583000e+00,6.580000e-01,6.392000e+00,4.400000e+01
50%,0.000000e+00,7.740200e+04,7.000000e-02,2.000000e-03,1.000000e-03,1.000000e-03,7.190000e-01,1.800000e-02,6.000000e-03,1.000000e-02,...,2.410300e+01,2.165000e+00,6.403000e+00,7.720000e-01,8.557100e+01,7.100000e-02,6.342000e+00,8.200000e-01,7.099000e+00,9.600000e+01
75%,0.000000e+00,7.911700e+04,9.500000e-02,4.000000e-03,1.000000e-03,1.000000e-02,1.000000e+00,2.100000e-02,7.000000e-03,7.400000e-02,...,2.915800e+01,2.481000e+00,7.072000e+00,9.020000e-01,9.172300e+01,2.650000e-01,7.074000e+00,9.660000e-01,8.136000e+00,1.370000e+02
max,1.000000e+00,8.080000e+04,8.800000e-01,7.500000e-02,1.090000e-01,4.900000e-02,1.871000e+00,1.150000e-01,2.900000e-02,4.930000e-01,...,7.960900e+01,4.695000e+00,1.565700e+01,4.692000e+00,9.758300e+01,2.984000e+00,1.565300e+01,2.511000e+00,3.136900e+01,8.070000e+02

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X= df.drop(['MOULD_FRONT_HEATLOSS'],axis=1).values
y= df['MOULD_FRONT_HEATLOSS'].values

In [ ]:
X_train, X_test ,y_train, y_test=train_test_split(X,y,test_size=0.1)

In [ ]:
df.shape

In [ ]:
y_train

In [ ]:
 X_test

In [ ]:
 y_train.head()

In [ ]:
scaler=MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled= scaler.transform(X_test)